### ISSUE TITLE
Push a notification to an alias

### ISSUE THREAD

**Issue by JochemR** [bnorton/push_bot#2]
Hi,

This looks like a great gem, but I have a question: why do I have to define a platform when I want to notify someone via an alias?

In my case the alias is connected to a user account, so the platform can change or be both when someone logs in on another device.

**Comment by JochemR** [comment]
I see now in the PushBot docs that a platform is required.
Can it be an array? So both iOS and Android?

**Comment by JochemR** [comment]
OK, I see in the PushBot docs that a platform is required. I tried defining the platform as an array with both iOS and Android and it seems to work. Thanks for this great gem!

**Comment by bnorton** [comment]
@JochemR You're welcome and thanks for continuing to look into this after you logged the issue.
